# Lesson 2) Label Encoding

## ~ Create a Dataset

In [4]:
import pandas as pd
dataset = {
    'Color':['Red', 'Blue', 'Green', 'Blue','Red','Green','Blue','Red','Green'],
    'Size':['Small', 'Medium', 'Large', 'Small','Medium','Large','Small','Medium','Large'],
    'City':['Delhi','Mumbai','Bangalore','Chennai','Hyderabad','Delhi','Chennai','Hyderabad','Mumbai'],
    'Price':[120,150,80,200,130,450,232,700,211],
    'Purchased':['Yes','No','No','Yes','Yes','No','No','Yes','No']
}

df=pd.DataFrame(dataset)
df

   Color    Size       City  Price Purchased
0    Red   Small      Delhi    120       Yes
1   Blue  Medium     Mumbai    150        No
2  Green   Large  Bangalore     80        No
3   Blue   Small    Chennai    200       Yes
4    Red  Medium  Hyderabad    130       Yes
5  Green   Large      Delhi    450        No
6   Blue   Small    Chennai    232        No
7    Red  Medium  Hyderabad    700       Yes
8  Green   Large     Mumbai    211        No

## ~ Definition of Label Encoding (Simple):
<p style="font-size: 17px;">Machine doesn't want text. It wants numbers only. <br>
    Converting categories into numbers, where each unique category gets a number.<br>
    The assigning of numbers is done by sorting of categories alphabetically.<br>
    For eg) <br>
    Red, Blue, Green. Blue-0, Green-1, Red-2<br>
    Yes, No. No-0, Yes-1 </p>

In [13]:
from sklearn.preprocessing import LabelEncoder

## ~ Practicing Label Encoding on Each Column

In [14]:
label_enc=LabelEncoder()

In [15]:
y=df['Purchased']

In [16]:
y_enc=label_enc.fit_transform(y)

In [17]:
y_enc

array([1, 0, 0, 1, 1, 0, 0, 1, 0])

In [12]:
z=df['Color']

In [18]:
z_enc=label_enc.fit_transform(z)

In [19]:
z_enc

array([2, 0, 1, 0, 2, 1, 0, 2, 1])

In [20]:
a=df['City']

In [21]:
a_enc=label_enc.fit_transform(a)

In [22]:
a_enc

array([2, 4, 0, 1, 3, 2, 1, 3, 4])

In [23]:
b=df['Size']

In [24]:
b_enc=label_enc.fit_transform(b)

In [25]:
b_enc

array([2, 1, 0, 2, 1, 0, 2, 1, 0])

## ~ Replacing Categories with Encoded values in the columns (ML Ready Dataset)

In [26]:
for col in ['Color','Size','City','Purchased']:
    le=LabelEncoder()
    df[col]=le.fit_transform(df[col])

In [27]:
df

   Color  Size  City  Price  Purchased
0      2     2     2    120          1
1      0     1     4    150          0
2      1     0     0     80          0
3      0     2     1    200          1
4      2     1     3    130          1
5      1     0     2    450          0
6      0     2     1    232          0
7      2     1     3    700          1
8      1     0     4    211          0