# Lesson 3) One Hot Encoding

## ~ Create a Dataset

In [1]:
import pandas as pd
dataset = {
    'Color':['Red', 'Blue', 'Green', 'Blue','Red','Green','Blue','Red','Green'],
    'Size':['Small', 'Medium', 'Large', 'Small','Medium','Large','Small','Medium','Large'],
    'City':['Delhi','Mumbai','Bangalore','Chennai','Hyderabad','Delhi','Chennai','Hyderabad','Mumbai'],
    'Price':[120,150,80,200,130,450,232,700,211],
    'Purchased':['Yes','No','No','Yes','Yes','No','No','Yes','No']
}

df=pd.DataFrame(dataset)
df

   Color    Size       City  Price Purchased
0    Red   Small      Delhi    120       Yes
1   Blue  Medium     Mumbai    150        No
2  Green   Large  Bangalore     80        No
3   Blue   Small    Chennai    200       Yes
4    Red  Medium  Hyderabad    130       Yes
5  Green   Large      Delhi    450        No
6   Blue   Small    Chennai    232        No
7    Red  Medium  Hyderabad    700       Yes
8  Green   Large     Mumbai    211        No

## ~ Definition of One Hot Encoding (Simple):
<p style="font-size: 17px;">Machines don’t understand text. They want numbers. <br>
    One-Hot Encoding is a way to convert each category into a separate column with 0 or 1.<br>
    This is just like a truth table in logic:<br>
    Row = individual example <br>
    Column = category <br>
    1 = “Yes, this example belongs to this category” <br>
    0 = “No, it doesn’t” <br>
   One-Hot Encoding Result: <br>
   <table border="1" cellpadding="5" cellspacing="0">
  <thead>
    <tr>
      <th>Row</th>
      <th>Blue</th>
      <th>Green</th>
      <th>Red</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <td>2</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <td>3</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <td>4</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

It means: Row 0 is Red Color, Row 1 is Blue, Row 2 is Green, Row 3 is Blue and Row 4 is Red</p>

In [2]:
from sklearn.preprocessing import OneHotEncoder

## ~ Practicing One Hot Encoding on Each Column

In [3]:
enc = OneHotEncoder()

In [10]:
enc_pur=pd.DataFrame(enc.fit_transform(df[["Purchased"]]).toarray())
enc_pur

     0    1
0  0.0  1.0
1  1.0  0.0
2  1.0  0.0
3  0.0  1.0
4  0.0  1.0
5  1.0  0.0
6  1.0  0.0
7  0.0  1.0
8  1.0  0.0

In [13]:
enc_col=pd.DataFrame(enc.fit_transform(df[["Color"]]).toarray())
enc_col

     0    1    2
0  0.0  0.0  1.0
1  1.0  0.0  0.0
2  0.0  1.0  0.0
3  1.0  0.0  0.0
4  0.0  0.0  1.0
5  0.0  1.0  0.0
6  1.0  0.0  0.0
7  0.0  0.0  1.0
8  0.0  1.0  0.0

In [14]:
enc_city=pd.DataFrame(enc.fit_transform(df[["City"]]).toarray())
enc_city

     0    1    2    3    4
0  0.0  0.0  1.0  0.0  0.0
1  0.0  0.0  0.0  0.0  1.0
2  1.0  0.0  0.0  0.0  0.0
3  0.0  1.0  0.0  0.0  0.0
4  0.0  0.0  0.0  1.0  0.0
5  0.0  0.0  1.0  0.0  0.0
6  0.0  1.0  0.0  0.0  0.0
7  0.0  0.0  0.0  1.0  0.0
8  0.0  0.0  0.0  0.0  1.0

In [15]:
enc_size=pd.DataFrame(enc.fit_transform(df[["Size"]]).toarray())
enc_size

     0    1    2
0  0.0  0.0  1.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  0.0  1.0  0.0
5  1.0  0.0  0.0
6  0.0  0.0  1.0
7  0.0  1.0  0.0
8  1.0  0.0  0.0

## ~ Replacing Categories with Encoded values in the columns (ML Ready Dataset)

In [24]:
df1=df.copy()
for col in ["Color","Size","City","Purchased"]:
    enc1=OneHotEncoder(sparse_output=False)
    encoded=enc1.fit_transform(df1[[col]])
    encode_df=pd.DataFrame(encoded, columns=enc1.get_feature_names_out([col]))  
    #get_feature_names_out() is a method to extract the col_feature as a name
    df1=pd.concat([df1.drop(col,axis=1),encode_df],axis=1)
df1

,Price,Color_Blue,Color_Green,Color_Red,Size_Large,Size_Medium,Size_Small,City_Bangalore,City_Chennai,City_Delhi,City_Hyderabad,City_Mumbai,Purchased_No,Purchased_Yes
0,120,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,150,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,80,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,200,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,130,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
5,450,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
6,232,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
7,700,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
8,211,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

## ~ Common Erros
### 1. df[] instead of df[[]] 
<p style="font-size:19px">
    Reason: df[] returns Series (1D) it contains shape(n,) <br>
            df[[]] returns DataFrame (2D) it contains shape(n,1) where 1 is Column <br>
            OneHotEncoder expects a 2D array as input: (n_samples, n_features) <br>
            So even though df is a DataFrame, selecting a single column with single brackets <br>
            returns a Series, not a DataFrame. That’s why we use double brackets for <br>
            OneHotEncoder.
</p>

In [8]:
enc_pur = pd.DataFrame(enc.fit_transform(df["Purchased"]))
enc_pur

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

### 2. Not using toarray() or OneHotEncoder(sparse_output=False)
<p style="font-size:19px">
    This is not an error but more on human readability. <br> 
    OneHotEncoder stores values in sparse matrix (Meaning: all zeroes are not shown) <br>
    To see zeroes we convert to array using toarray() <br>
    <br>
    Without toarray(): <br>
    (row,col where 1 is) 1.0 <br>
    eg) (0,2) 1.0   here it means for row 0. at col 2 is 1. Meaning row 0 is Red color. <br>
        (1,0) 1.0   here for row 1. st col 0 is 1. Meaning row 1 is Blue <br>
    <br>
    With toarray() or sparse_output=False: <br>
    [[0, 0, 1]  <br>
     [1, 0, 0]]  <br>
    <br>
    As we are converting it to Dataframe to show our output, we'll use toarray() or sparse_output=False. But do the same<br>
</p>

In [9]:
enc_pur = pd.DataFrame(enc.fit_transform(df[["Purchased"]]))
enc_pur

               0
0    (0, 1)\t1.0
1    (0, 0)\t1.0
2    (0, 0)\t1.0
3    (0, 1)\t1.0
4    (0, 1)\t1.0
5    (0, 0)\t1.0
6    (0, 0)\t1.0
7    (0, 1)\t1.0
8    (0, 0)\t1.0

<h3>Encoding Rules for ML</h3>
<table border="1" cellpadding="5">
<tr>
<th>Encoding</th>
<th>Use for</th>
<th>Do NOT use for</th>
<th>Why</th>
<th>Recommended Algorithms</th>
</tr>
<tr>
<td>Label Encoding</td>
<td>Ordinal features (with order, e.g., Size: Small, Medium, Large)</td>
<td>Nominal features (without order, e.g., Color, City)</td>
<td>Numbers imply order; works only when order matters</td>
<td>Decision Trees, Random Forests, XGBoost (can handle numeric labels)</td>
</tr>
<tr>
<td>One-Hot Encoding</td>
<td>Nominal features (no order, e.g., Color, City)</td>
<td>Ordinal features (with order, e.g., Size)</td>
<td>Creates independent columns; loses order info if ordinal</td>
<td>Linear Regression, Logistic Regression, KNN, Neural Networks</td>
</tr>
</table>

<p>Note: For ordinal features where order matters, manually map categories to numbers instead of using LabelEncoder.  
Example: <code>{"Small": 0, "Medium": 1, "Large": 2}</code></p>