# Lesson 4) Train Test Split

## ~ Import pandas to read csv and train_test_split from sklearn

In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split

## ~ Read the csv

In [19]:
df=pd.read_csv(r"C:\Users\study\Desktop\Learning scikit-learn\data\student_grades_50.csv")
df.head()

   Hours_Studied  Attendance  Previous_Grades  Pass
0              7          96               90     1
1              4          84               56     1
2              8          63               47     1
3              5          66               74     1
4              7          85               74     1

In [21]:
df.shape

(50, 4)

## ~ Determining X and y
<p><strong>X (features/inputs):</strong> The data used to make predictions. Example: hours studied, attendance, previous grades.</p>

<p><strong>y (target/output):</strong> The value we want the model to predict. Example: pass/fail or final grade.</p>

<p><strong>How to determine X and y from a dataset:</strong></p>
<ul>
  <li>y: Choose the column you want to predict.</li>
  <li>X: Choose all other columns that help predict y.</li>
</ul>

In [26]:
X=df[['Hours_Studied','Attendance','Previous_Grades']]
X.head()

   Hours_Studied  Attendance  Previous_Grades
0              7          96               90
1              4          84               56
2              8          63               47
3              5          66               74
4              7          85               74

In [27]:
X.shape

(50, 3)

In [28]:
y=df[['Pass']]
y.head()

   Pass
0     1
1     1
2     1
3     1
4     1

In [29]:
y.shape

(50, 1)

## ~ Performing train_test_split
<p>This line splits the dataset into training and testing sets:</p>

<ul>
  <li><strong>X_train:</strong> Features used to <em>train the model</em> (80% of data).</li>
  <li><strong>X_test:</strong> Features used to <em>test the model</em> (20% of data).</li>
  <li><strong>y_train:</strong> Target values for training.</li>
  <li><strong>y_test:</strong> Target values for testing.</li>
</ul>

<p><strong>Parameters:</strong></p>
<ul>
  <li><code>test_size=0.2</code> → 20% of data for testing.</li>
  <li><code>random_state=14</code> → ensures the split is reproducible.</li>
</ul>

<p>This ensures the model is trained on one set of data and evaluated on a separate unseen set to check performance.</p>

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=14
)

<h4>Train-Test Split Explanation</h4>
<p>When we split the dataset using <code>train_test_split</code>:</p>
<ul>
  <li><strong>Shuffle:</strong> Rows are randomly mixed before splitting (default behavior) to avoid bias from the original order. Default is True but if you don't want then you keep it false.</li>
  <li><strong>Shape change:</strong> The original dataset is divided into training and testing sets, so the number of rows in <code>X_train</code> and <code>X_test</code> changes according to <code>test_size</code>, but the number of columns stays the same.</li>
</ul>

In [33]:
print(X_train.head())
print("X_train Shape:", X_train.shape)
print(X_test.head())
print("X_test Shape:", X_test.shape)
print(y_train.head())
print("y_train Shape:", y_train.shape)
print(y_test.head())
print("y_test Shape:", y_test.shape)

    Hours_Studied  Attendance  Previous_Grades
36              9          90               40
44             10          73               54
17              8          59               73
11              8          53               80
39              4          94               94
X_train Shape: (40, 3)
    Hours_Studied  Attendance  Previous_Grades
47              4          57               81
21              1          97               62
14              6          75               48
30              9          67               40
37              7          78               44
X_test Shape: (10, 3)
    Pass
36     1
44     1
17     1
11     1
39     1
y_train Shape: (40, 1)
    Pass
47     0
21     0
14     1
30     1
37     1
y_test Shape: (10, 1)

<h4>Using <code>describe()</code> in Machine Learning</h4>

<p>The <code>describe()</code> method provides <strong>summary statistics</strong> for numeric columns in a dataset:</p>

<ul>
  <li><strong>count:</strong> Number of non-missing values</li>
  <li><strong>mean:</strong> Average value</li>
  <li><strong>std:</strong> Standard deviation (spread of data)</li>
  <li><strong>min / max:</strong> Smallest and largest values</li>
  <li><strong>25%, 50%, 75%:</strong> Percentiles (quartiles) showing data distribution</li>
</ul>

<p><strong>Why it’s useful for ML:</strong></p>
<ul>
  <li>Helps understand feature distributions before training a model</li>
  <li>Identifies outliers, ranges, and spread of data</li>
  <li>Aids in feature scaling and preprocessing decisions</li>
</ul>

In [35]:
X_test.describe()

       Hours_Studied  Attendance  Previous_Grades
count      10.000000   10.000000        10.000000
mean        5.300000   72.300000        61.600000
std         2.907844   14.900037        20.073199
min         1.000000   50.000000        40.000000
25%         3.250000   63.000000        47.250000
50%         5.000000   71.000000        54.500000
75%         7.750000   82.500000        76.250000
max         9.000000   97.000000        98.000000

In [37]:
X_test.describe()

       Hours_Studied  Attendance  Previous_Grades
count      10.000000   10.000000        10.000000
mean        5.300000   72.300000        61.600000
std         2.907844   14.900037        20.073199
min         1.000000   50.000000        40.000000
25%         3.250000   63.000000        47.250000
50%         5.000000   71.000000        54.500000
75%         7.750000   82.500000        76.250000
max         9.000000   97.000000        98.000000

In [38]:
y_train.describe()

            Pass
count  40.000000
mean    0.775000
std     0.422902
min     0.000000
25%     1.000000
50%     1.000000
75%     1.000000
max     1.000000

In [39]:
y_test.describe()

            Pass
count  10.000000
mean    0.700000
std     0.483046
min     0.000000
25%     0.250000
50%     1.000000
75%     1.000000
max     1.000000